// Mocks generated by Mockito 5.4.4 from annotations
// in simple_otp/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:simple_otp/manager/storage_manager.dart' as _i2;
import 'package:simple_otp/model/otp_secret.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [StorageManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageManager extends _i1.Mock implements _i2.StorageManager {
  MockStorageManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.OTPSecret>> readDatabase() => (super.noSuchMethod(
        Invocation.method(
          #readDatabase,
          [],
        ),
        returnValue: _i3.Future<List<_i4.OTPSecret>>.value(<_i4.OTPSecret>[]),
      ) as _i3.Future<List<_i4.OTPSecret>>);

  @override
  _i3.Future<_i5.Uint8List> encrypt(String? jsonString) => (super.noSuchMethod(
        Invocation.method(
          #encrypt,
          [jsonString],
        ),
        returnValue: _i3.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
      ) as _i3.Future<_i5.Uint8List>);

  @override
  _i3.Future<String> decrypt(_i5.Uint8List? data) => (super.noSuchMethod(
        Invocation.method(
          #decrypt,
          [data],
        ),
        returnValue: _i3.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #decrypt,
            [data],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> writeDatabase(List<_i4.OTPSecret>? secrets) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeDatabase,
          [secrets],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
