// Mocks generated by Mockito 5.4.4 from annotations
// in simple_otp/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:simple_otp/manager/storage_manager.dart' as _i2;
import 'package:simple_otp/model/otp_secret.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [StorageManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageManager extends _i1.Mock implements _i2.StorageManager {
  MockStorageManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.OTPSecret>> readDatabase() => (super.noSuchMethod(
        Invocation.method(
          #readDatabase,
          [],
        ),
        returnValue: _i3.Future<List<_i4.OTPSecret>>.value(<_i4.OTPSecret>[]),
      ) as _i3.Future<List<_i4.OTPSecret>>);

  @override
  _i3.Future<void> writeDatabase(List<_i4.OTPSecret>? secrets) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeDatabase,
          [secrets],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  String writeToJSON(List<_i4.OTPSecret>? secrets) => (super.noSuchMethod(
        Invocation.method(
          #writeToJSON,
          [secrets],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #writeToJSON,
            [secrets],
          ),
        ),
      ) as String);

  @override
  List<_i4.OTPSecret> readFromJson(String? jsonString) => (super.noSuchMethod(
        Invocation.method(
          #readFromJson,
          [jsonString],
        ),
        returnValue: <_i4.OTPSecret>[],
      ) as List<_i4.OTPSecret>);

  @override
  _i3.Future<bool> doesDatabaseExist() => (super.noSuchMethod(
        Invocation.method(
          #doesDatabaseExist,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
