name: simple-otp
version: 1.0.0
summary: Simple OTP
description: Authy replacement

confinement: strict
base: core22
grade: stable

slots:
  dbus-simple-otp: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: io.github.simple-otp
    
apps:
  Simple OTP:
    command: simple_otp
    extensions: [gnome] # gnome includes the libraries required by flutter
    plugs:
    - network
    slots:
      - dbus-simple-otp
parts:
  simple-otp-app:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application