name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: update_ubuntu
      shell: bash 
      run: sudo apt-get update && sudo apt-get install -y libasound2-dev lld libudev-dev libgtk-3-dev
      
    - name: Build
      working-directory: ./rust
      run: cargo build --verbose
      
    - name: Run tests
      working-directory: ./rust
      run: cargo test --verbose
